exports.seed = async function (knex) {
  await knex('media').del();
  await knex('users').del();

  // Fern — Manager (default password: fuego2024)
  await knex('users').insert([
    {
      id: 1,
      name: 'Fern',
      email: 'fjchavez01@gmail.com',
      password_hash: '$2b$12$nVpQwX9nLQ0RGZ6AP8hr1.MTA5l6mwZRhxHWWyOP5EEBxkZmq9PnG',
      permission_level: 'manager',
      is_active: true,
    },
  ]);

  const now = new Date().toISOString().slice(0, 10);

  await knex('media').insert([
    // ── HERO ────────────────────────────────────────────────────────────────
    {
      title: 'Hero Main',
      description: 'Fuego Entertainment hero banner image.',
      filename: 'hero-main.jpg',
      filepath: '/images/hero-main.jpg',
      mimetype: 'image/jpeg',
      category: 'hero',
      price: null,
      event_date: null,
      tags: 'hero,banner',
      is_active: true,
      sort_order: 0,
    },

    // ── COLLECTIONS ─────────────────────────────────────────────────────────
    {
      title: 'Archive Fridays — Collection Cover',
      description: 'Cover image for the Archive Fridays weekly collection.',
      filename: 'archive-fridays.webp',
      filepath: '/images/collections/archive-fridays.webp',
      mimetype: 'image/webp',
      category: 'collections',
      price: null,
      event_date: null,
      tags: 'collection,archive,fridays',
      is_active: true,
      sort_order: 1,
    },
    {
      title: 'Traviesa Saturdays — Collection Cover',
      description: 'Cover image for the Traviesa Saturdays weekly collection.',
      filename: 'traviesa-saturdays.jpg',
      filepath: '/images/collections/traviesa-saturdays.jpg',
      mimetype: 'image/jpeg',
      category: 'collections',
      price: null,
      event_date: null,
      tags: 'collection,traviesa,saturdays',
      is_active: true,
      sort_order: 2,
    },
    {
      title: 'Deseo Sundays — Collection Cover',
      description: 'Cover image for the Deseo Sundays weekly collection.',
      filename: 'deseo-sundays.png',
      filepath: '/images/collections/deseo-sundays.png',
      mimetype: 'image/png',
      category: 'collections',
      price: null,
      event_date: null,
      tags: 'collection,deseo,sundays',
      is_active: true,
      sort_order: 3,
    },

    // ── ARCHIVE ──────────────────────────────────────────────────────────────
    {
      title: 'Archive Photo 1',
      description: 'Archive Fridays event photo.',
      filename: 'archive-1.jpg',
      filepath: '/images/archive/archive-1.jpg',
      mimetype: 'image/jpeg',
      category: 'archive',
      price: null,
      event_date: null,
      tags: 'archive,fridays',
      is_active: true,
      sort_order: 1,
    },
    {
      title: 'Archive Photo 2',
      description: 'Archive Fridays event photo.',
      filename: 'archive-2.jpg',
      filepath: '/images/archive/archive-2.jpg',
      mimetype: 'image/jpeg',
      category: 'archive',
      price: null,
      event_date: null,
      tags: 'archive,fridays',
      is_active: true,
      sort_order: 2,
    },
    {
      title: 'Archive Photo 3',
      description: 'Archive Fridays event photo.',
      filename: 'archive-3.webp',
      filepath: '/images/archive/archive-3.webp',
      mimetype: 'image/webp',
      category: 'archive',
      price: null,
      event_date: null,
      tags: 'archive,fridays',
      is_active: true,
      sort_order: 3,
    },
    {
      title: 'Archive Photo 4',
      description: 'Archive Fridays event photo.',
      filename: 'archive-4.jpg',
      filepath: '/images/archive/archive-4.jpg',
      mimetype: 'image/jpeg',
      category: 'archive',
      price: null,
      event_date: null,
      tags: 'archive,fridays',
      is_active: true,
      sort_order: 4,
    },
    {
      title: 'Archive Photo 5',
      description: 'Archive Fridays event photo.',
      filename: 'archive-5.jpg',
      filepath: '/images/archive/archive-5.jpg',
      mimetype: 'image/jpeg',
      category: 'archive',
      price: null,
      event_date: null,
      tags: 'archive,fridays',
      is_active: true,
      sort_order: 5,
    },

    // ── TRAVIESA ─────────────────────────────────────────────────────────────
    {
      title: 'Traviesa Photo 1',
      description: 'Traviesa Saturdays event photo.',
      filename: 'traviesa-1.jpg',
      filepath: '/images/traviesa/traviesa-1.jpg',
      mimetype: 'image/jpeg',
      category: 'traviesa',
      price: null,
      event_date: null,
      tags: 'traviesa,saturdays',
      is_active: true,
      sort_order: 1,
    },
    {
      title: 'Traviesa Photo 2',
      description: 'Traviesa Saturdays event photo.',
      filename: 'traviesa-2.jpg',
      filepath: '/images/traviesa/traviesa-2.jpg',
      mimetype: 'image/jpeg',
      category: 'traviesa',
      price: null,
      event_date: null,
      tags: 'traviesa,saturdays',
      is_active: true,
      sort_order: 2,
    },
    {
      title: 'Traviesa Photo 3',
      description: 'Traviesa Saturdays event photo.',
      filename: 'traviesa-3.jpg',
      filepath: '/images/traviesa/traviesa-3.jpg',
      mimetype: 'image/jpeg',
      category: 'traviesa',
      price: null,
      event_date: null,
      tags: 'traviesa,saturdays',
      is_active: true,
      sort_order: 3,
    },
    {
      title: 'Traviesa Photo 4',
      description: 'Traviesa Saturdays event photo.',
      filename: 'traviesa-4.jpg',
      filepath: '/images/traviesa/traviesa-4.jpg',
      mimetype: 'image/jpeg',
      category: 'traviesa',
      price: null,
      event_date: null,
      tags: 'traviesa,saturdays',
      is_active: true,
      sort_order: 4,
    },

    // ── DESEO ─────────────────────────────────────────────────────────────────
    {
      title: 'Deseo Photo 1',
      description: 'Deseo Sundays event photo.',
      filename: 'deseo-1.jpg',
      filepath: '/images/deseo/deseo-1.jpg',
      mimetype: 'image/jpeg',
      category: 'deseo',
      price: null,
      event_date: null,
      tags: 'deseo,sundays',
      is_active: true,
      sort_order: 1,
    },
    {
      title: 'Deseo Photo 2',
      description: 'Deseo Sundays event photo.',
      filename: 'deseo-2.jpg',
      filepath: '/images/deseo/deseo-2.jpg',
      mimetype: 'image/jpeg',
      category: 'deseo',
      price: null,
      event_date: null,
      tags: 'deseo,sundays',
      is_active: true,
      sort_order: 2,
    },
    {
      title: 'Deseo Photo 3',
      description: 'Deseo Sundays event photo.',
      filename: 'deseo-3.jpg',
      filepath: '/images/deseo/deseo-3.jpg',
      mimetype: 'image/jpeg',
      category: 'deseo',
      price: null,
      event_date: null,
      tags: 'deseo,sundays',
      is_active: true,
      sort_order: 3,
    },
    {
      title: 'Deseo Photo 4',
      description: 'Deseo Sundays event photo.',
      filename: 'deseo-4.jpg',
      filepath: '/images/deseo/deseo-4.jpg',
      mimetype: 'image/jpeg',
      category: 'deseo',
      price: null,
      event_date: null,
      tags: 'deseo,sundays',
      is_active: true,
      sort_order: 4,
    },

    // ── EVENTS ────────────────────────────────────────────────────────────────
    {
      title: 'Event 1',
      description: 'Fuego Entertainment event flyer.',
      filename: 'event-1.jpg',
      filepath: '/images/events/event-1.jpg',
      mimetype: 'image/jpeg',
      category: 'events',
      price: null,
      event_date: null,
      tags: 'event,flyer',
      is_active: true,
      sort_order: 1,
    },
    {
      title: 'Event 2',
      description: 'Fuego Entertainment event flyer.',
      filename: 'event-2.jpg',
      filepath: '/images/events/event-2.jpg',
      mimetype: 'image/jpeg',
      category: 'events',
      price: null,
      event_date: null,
      tags: 'event,flyer',
      is_active: true,
      sort_order: 2,
    },
    {
      title: 'Event 3',
      description: 'Fuego Entertainment event flyer.',
      filename: 'event-3.webp',
      filepath: '/images/events/event-3.webp',
      mimetype: 'image/webp',
      category: 'events',
      price: null,
      event_date: null,
      tags: 'event,flyer',
      is_active: true,
      sort_order: 3,
    },

    // ── PRODUCTS ─────────────────────────────────────────────────────────────
    {
      title: 'Archive Fridays — Table Package',
      description: 'VIP table package for Archive Fridays. Includes bottle service for up to 8 guests.',
      filename: 'archive-fridays-58.png',
      filepath: '/images/products/archive-fridays-58.png',
      mimetype: 'image/png',
      category: 'products',
      price: 58.00,
      event_date: null,
      tags: 'product,archive,fridays,table,vip',
      is_active: true,
      sort_order: 1,
    },
    {
      title: 'Banda Night',
      description: 'Special Banda Night event ticket. Live banda performance with open bar.',
      filename: 'banda-night.png',
      filepath: '/images/products/banda-night.png',
      mimetype: 'image/png',
      category: 'products',
      price: 35.00,
      event_date: null,
      tags: 'product,banda,event,ticket',
      is_active: true,
      sort_order: 2,
    },
  ]);
};
